# Generated by Django 5.2.5 on 2025-09-01 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('minimum_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, help_text='Maximum withdrawal per month', max_digits=10)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Savings Product',
                'verbose_name_plural': 'Savings Products',
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate percentage', max_digits=5)),
                ('date_opened', models.DateField(default=django.utils.timezone.now)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account', to='members.member')),
            ],
            options={
                'verbose_name': 'Savings Account',
                'verbose_name_plural': 'Savings Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('compulsory', 'Compulsory Savings'), ('voluntary', 'Voluntary Savings'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest Payment'), ('penalty', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_savings', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to='savings.savingsaccount')),
            ],
            options={
                'verbose_name': 'Savings Transaction',
                'verbose_name_plural': 'Savings Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
