# Generated by Django 4.2.7 on 2025-09-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount available for withdrawal (balance - collateral)', max_digits=15),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='collateral_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount held as collateral for active loans', max_digits=15),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='has_active_loan',
            field=models.BooleanField(default=False, help_text='Whether member has an active loan'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='is_loan_repayment',
            field=models.BooleanField(default=False, help_text='Whether this transaction is for loan repayment'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_repayments', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='repayment_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest amount repaid', max_digits=12),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='repayment_principal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Principal amount repaid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('compulsory', 'Compulsory Savings'), ('voluntary', 'Voluntary Savings'), ('withdrawal', 'Withdrawal'), ('interest', 'Interest Payment'), ('penalty', 'Penalty'), ('loan_repayment', 'Loan Repayment'), ('collateral', 'Collateral (Pre-loan Savings)')], max_length=20),
        ),
    ]
