# Generated by Django 5.2.5 on 2025-09-01 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('maximum_tenure_months', models.PositiveIntegerField(help_text='Maximum loan tenure in months')),
                ('processing_fee_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Processing fee as percentage', max_digits=5)),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('minimum_savings_multiple', models.DecimalField(decimal_places=2, default=2.0, help_text='Minimum savings as multiple of loan amount', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('guarantor_name', models.CharField(blank=True, max_length=100)),
                ('guarantor_phone', models.CharField(blank=True, max_length=17)),
                ('guarantor_address', models.TextField(blank=True)),
                ('guarantor_relationship', models.CharField(blank=True, max_length=100)),
                ('principal_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanproduct')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
