# Generated by Django 4.2.7 on 2025-09-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='processing_fee_rate',
        ),
    ]
