# Generated by Django 4.2.7 on 2025-09-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_processing_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='minimum_savings_multiple',
        ),
    ]
