# Generated by Django 4.2.7 on 2025-09-26 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='member',
            name='entrance_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when member joined the cooperative'),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly savings commitment amount', max_digits=12),
        ),
    ]
